name: Data Pipeline
on:
  schedule:
    - cron: "*/4 * * * *"  # Runs every 5 minutes (GitHub's minimum interval)
  workflow_dispatch:       # Allow manual triggers

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false # important!
          fetch-depth: 0 # Needed to retrieve all history, especially for auto-versioning scripts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scripts
        run: |
          python fetch_data.py
          python convert_to_csv.py

      - name: Configure Git user
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add processed_data.csv
          git commit -m "Auto-update CSV" || echo "No changes to commit."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
